version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
  app:
    build: loja
    restart: always
    ports:
      - 80:80
